apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.serviceName }}
  labels:
    app: redis
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.redis.port }}
  clusterIP: None
  selector:
    app: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: {{ .Values.redis.serviceName | quote }} 
  replicas: {{ .Values.redis.replicaCount }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.port }}